[package]
name = "nestmtx-streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
gstreamer = "0.17"
rust_socketio = "*"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }