blank_issues_enabled: false

contact_links:
  - name: Question
    url: https://github.com/NestMTX/app/discussions?category=questions
    about: Ask the community for help
  - name: Discord
    url: https://discord.gg/hMAEuNa4Fd
    about: Chat with the community on Discord
  - name: Documentation
    url: https://nestmtx.com/
    about: Read the documentation
