export default {
  ab: {
    iso: 'ab',
    english: 'Abkhazian',
    local: 'аҧсуа бызшәа',
    rtl: false,
  },
  aa: {
    iso: 'aa',
    english: 'Afar',
    local: 'Afaraf',
    rtl: false,
  },
  af: {
    iso: 'af',
    english: 'Afrikaans',
    local: 'Afrikaans',
    rtl: false,
  },
  ak: {
    iso: 'ak',
    english: 'Akan',
    local: 'Akan',
    rtl: false,
  },
  sq: {
    iso: 'sq',
    english: 'Albanian',
    local: 'Shqip',
    rtl: false,
  },
  am: {
    iso: 'am',
    english: 'Amharic',
    local: 'አማርኛ',
    rtl: false,
  },
  ar: {
    iso: 'ar',
    english: 'Arabic',
    local: 'العربية',
    rtl: true,
  },
  an: {
    iso: 'an',
    english: 'Aragonese',
    local: 'aragonés',
    rtl: false,
  },
  hy: {
    iso: 'hy',
    english: 'Armenian',
    local: 'Հայերեն',
    rtl: false,
  },
  as: {
    iso: 'as',
    english: 'Assamese',
    local: 'অসমীয়া',
    rtl: false,
  },
  av: {
    iso: 'av',
    english: 'Avaric',
    local: 'магӀарул мацӀ',
    rtl: false,
  },
  ae: {
    iso: 'ae',
    english: 'Avestan',
    local: 'avesta',
    rtl: false,
  },
  ay: {
    iso: 'ay',
    english: 'Aymara',
    local: 'aymar aru',
    rtl: false,
  },
  az: {
    iso: 'az',
    english: 'Azerbaijani',
    local: 'azərbaycan dili',
    rtl: false,
  },
  bm: {
    iso: 'bm',
    english: 'Bambara',
    local: 'bamanankan',
    rtl: false,
  },
  ba: {
    iso: 'ba',
    english: 'Bashkir',
    local: 'башҡорт теле',
    rtl: false,
  },
  eu: {
    iso: 'eu',
    english: 'Basque',
    local: 'euskara, euskera',
    rtl: false,
  },
  be: {
    iso: 'be',
    english: 'Belarusian',
    local: 'беларуская мова',
    rtl: false,
  },
  bn: {
    iso: 'bn',
    english: 'Bengali',
    local: 'বাংলা',
    rtl: false,
  },
  bh: {
    iso: 'bh',
    english: 'Bihari languages',
    local: 'भोजपुरी',
    rtl: false,
  },
  bi: {
    iso: 'bi',
    english: 'Bislama',
    local: 'Bislama',
    rtl: false,
  },
  bs: {
    iso: 'bs',
    english: 'Bosnian',
    local: 'bosanski jezik',
    rtl: false,
  },
  br: {
    iso: 'br',
    english: 'Breton',
    local: 'brezhoneg',
    rtl: false,
  },
  bg: {
    iso: 'bg',
    english: 'Bulgarian',
    local: 'български език',
    rtl: false,
  },
  my: {
    iso: 'my',
    english: 'Burmese',
    local: 'ဗမာစာ',
    rtl: false,
  },
  ca: {
    iso: 'ca',
    english: 'Catalan',
    local: 'català',
    rtl: false,
  },
  ch: {
    iso: 'ch',
    english: 'Chamorro',
    local: 'Chamoru',
    rtl: false,
  },
  ce: {
    iso: 'ce',
    english: 'Chechen',
    local: 'нохчийн мотт',
    rtl: false,
  },
  ny: {
    iso: 'ny',
    english: 'Chichewa',
    local: 'chiCheŵa',
    rtl: false,
  },
  zh: {
    iso: 'zh',
    english: 'Chinese',
    local: '中文',
    rtl: false,
  },
  cv: {
    iso: 'cv',
    english: 'Chuvash',
    local: 'чӑваш чӗлхи',
    rtl: false,
  },
  kw: {
    iso: 'kw',
    english: 'Cornish',
    local: 'Kernewek',
    rtl: false,
  },
  co: {
    iso: 'co',
    english: 'Corsican',
    local: 'corsu',
    rtl: false,
  },
  cr: {
    iso: 'cr',
    english: 'Cree',
    local: 'ᓀᐦᐃᔭᐍᐏᐣ',
    rtl: false,
  },
  hr: {
    iso: 'hr',
    english: 'Croatian',
    local: 'hrvatski jezik',
    rtl: false,
  },
  cs: {
    iso: 'cs',
    english: 'Czech',
    local: 'čeština',
    rtl: false,
  },
  da: {
    iso: 'da',
    english: 'Danish',
    local: 'dansk',
    rtl: false,
  },
  dv: {
    iso: 'dv',
    english: 'Divehi',
    local: 'ދިވެހި',
    rtl: true,
  },
  nl: {
    iso: 'nl',
    english: 'Dutch',
    local: 'Nederlands',
    rtl: false,
  },
  dz: {
    iso: 'dz',
    english: 'Dzongkha',
    local: 'རྫོང་ཁ',
    rtl: false,
  },
  en: {
    iso: 'en',
    english: 'English',
    local: 'English',
    rtl: false,
  },
  eo: {
    iso: 'eo',
    english: 'Esperanto',
    local: 'Esperanto',
    rtl: false,
  },
  et: {
    iso: 'et',
    english: 'Estonian',
    local: 'eesti',
    rtl: false,
  },
  ee: {
    iso: 'ee',
    english: 'Ewe',
    local: 'Eʋegbe',
    rtl: false,
  },
  fo: {
    iso: 'fo',
    english: 'Faroese',
    local: 'føroyskt',
    rtl: false,
  },
  fj: {
    iso: 'fj',
    english: 'Fijian',
    local: 'vosa Vakaviti',
    rtl: false,
  },
  fi: {
    iso: 'fi',
    english: 'Finnish',
    local: 'suomi',
    rtl: false,
  },
  fr: {
    iso: 'fr',
    english: 'French',
    local: 'français',
    rtl: false,
  },
  ff: {
    iso: 'ff',
    english: 'Fulah',
    local: 'Fulfulde',
    rtl: false,
  },
  gl: {
    iso: 'gl',
    english: 'Galician',
    local: 'Galego',
    rtl: false,
  },
  ka: {
    iso: 'ka',
    english: 'Georgian',
    local: 'ქართული',
    rtl: false,
  },
  de: {
    iso: 'de',
    english: 'German',
    local: 'Deutsch',
    rtl: false,
  },
  el: {
    iso: 'el',
    english: 'Greek',
    local: 'ελληνικά',
    rtl: false,
  },
  gn: {
    iso: 'gn',
    english: 'Guarani',
    local: "Avañe'ẽ",
    rtl: false,
  },
  gu: {
    iso: 'gu',
    english: 'Gujarati',
    local: 'ગુજરાતી',
    rtl: false,
  },
  ht: {
    iso: 'ht',
    english: 'Haitian',
    local: 'Kreyòl ayisyen',
    rtl: false,
  },
  ha: {
    iso: 'ha',
    english: 'Hausa',
    local: 'هَوُسَ',
    rtl: false,
  },
  he: {
    iso: 'he',
    english: 'Hebrew',
    local: 'עברית',
    rtl: true,
  },
  hz: {
    iso: 'hz',
    english: 'Herero',
    local: 'Otjiherero',
    rtl: false,
  },
  hi: {
    iso: 'hi',
    english: 'Hindi',
    local: 'हिन्दी',
    rtl: false,
  },
  ho: {
    iso: 'ho',
    english: 'Hiri Motu',
    local: 'Hiri Motu',
    rtl: false,
  },
  hu: {
    iso: 'hu',
    english: 'Hungarian',
    local: 'magyar',
    rtl: false,
  },
  id: {
    iso: 'id',
    english: 'Indonesian',
    local: 'Bahasa Indonesia',
    rtl: false,
  },
  ga: {
    iso: 'ga',
    english: 'Irish',
    local: 'Gaeilge',
    rtl: false,
  },
  ig: {
    iso: 'ig',
    english: 'Igbo',
    local: 'Asụsụ Igbo',
    rtl: false,
  },
  ik: {
    iso: 'ik',
    english: 'Inupiaq',
    local: 'Iñupiaq',
    rtl: false,
  },
  io: {
    iso: 'io',
    english: 'Ido',
    local: 'Ido',
    rtl: false,
  },
  is: {
    iso: 'is',
    english: 'Icelandic',
    local: 'Íslenska',
    rtl: false,
  },
  it: {
    iso: 'it',
    english: 'Italian',
    local: 'Italiano',
    rtl: false,
  },
  iu: {
    iso: 'iu',
    english: 'Inuktitut',
    local: 'ᐃᓄᒃᑎᑐᑦ',
    rtl: false,
  },
  ja: {
    iso: 'ja',
    english: 'Japanese',
    local: '日本語 (にほんご)',
    rtl: false,
  },
  jv: {
    iso: 'jv',
    english: 'Javanese',
    local: 'ꦧꦱꦗꦮ',
    rtl: false,
  },
  kl: {
    iso: 'kl',
    english: 'Kalaallisut',
    local: 'kalaallisut',
    rtl: false,
  },
  kn: {
    iso: 'kn',
    english: 'Kannada',
    local: 'ಕನ್ನಡ',
    rtl: false,
  },
  kr: {
    iso: 'kr',
    english: 'Kanuri',
    local: 'Kanuri',
    rtl: false,
  },
  ks: {
    iso: 'ks',
    english: 'Kashmiri',
    local: 'कश्मीरी, كشميري‎',
    rtl: false,
  },
  kk: {
    iso: 'kk',
    english: 'Kazakh',
    local: 'қазақ тілі',
    rtl: false,
  },
  km: {
    iso: 'km',
    english: 'Central Khmer',
    local: 'ខ្មែរ',
    rtl: false,
  },
  ki: {
    iso: 'ki',
    english: 'Kikuyu',
    local: 'Gĩkũyũ',
    rtl: false,
  },
  rw: {
    iso: 'rw',
    english: 'Kinyarwanda',
    local: 'Ikinyarwanda',
    rtl: false,
  },
  ky: {
    iso: 'ky',
    english: 'Kirghiz',
    local: 'Кыргызча',
    rtl: false,
  },
  kv: {
    iso: 'kv',
    english: 'Komi',
    local: 'коми кыв',
    rtl: false,
  },
  kg: {
    iso: 'kg',
    english: 'Kongo',
    local: 'Kikongo',
    rtl: false,
  },
  ko: {
    iso: 'ko',
    english: 'Korean',
    local: '한국어',
    rtl: false,
  },
  ku: {
    iso: 'ku',
    english: 'Kurdish',
    local: 'کوردی‎',
    rtl: true,
  },
  kj: {
    iso: 'kj',
    english: 'Kuanyama',
    local: 'Kuanyama',
    rtl: false,
  },
  la: {
    iso: 'la',
    english: 'Latin',
    local: 'latine',
    rtl: false,
  },
  lb: {
    iso: 'lb',
    english: 'Luxembourgish',
    local: 'Lëtzebuergesch',
    rtl: false,
  },
  lg: {
    iso: 'lg',
    english: 'Ganda',
    local: 'Luganda',
    rtl: false,
  },
  li: {
    iso: 'li',
    english: 'Limburgan',
    local: 'Limburgs',
    rtl: false,
  },
  ln: {
    iso: 'ln',
    english: 'Lingala',
    local: 'Lingála',
    rtl: false,
  },
  lo: {
    iso: 'lo',
    english: 'Lao',
    local: 'ພາສາລາວ',
    rtl: false,
  },
  lt: {
    iso: 'lt',
    english: 'Lithuanian',
    local: 'lietuvių kalba',
    rtl: false,
  },
  lu: {
    iso: 'lu',
    english: 'Luba-Katanga',
    local: 'Kiluba',
    rtl: false,
  },
  lv: {
    iso: 'lv',
    english: 'Latvian',
    local: 'latviešu valoda',
    rtl: false,
  },
  gv: {
    iso: 'gv',
    english: 'Manx',
    local: 'Gaelg',
    rtl: false,
  },
  mk: {
    iso: 'mk',
    english: 'Macedonian',
    local: 'македонски јазик',
    rtl: false,
  },
  mg: {
    iso: 'mg',
    english: 'Malagasy',
    local: 'fiteny malagasy',
    rtl: false,
  },
  ms: {
    iso: 'ms',
    english: 'Malay',
    local: 'Melayu',
    rtl: false,
  },
  ml: {
    iso: 'ml',
    english: 'Malayalam',
    local: 'മലയാളം',
    rtl: false,
  },
  mt: {
    iso: 'mt',
    english: 'Maltese',
    local: 'Malti',
    rtl: false,
  },
  mi: {
    iso: 'mi',
    english: 'Maori',
    local: 'te reo Māori',
    rtl: false,
  },
  mr: {
    iso: 'mr',
    english: 'Marathi',
    local: 'मराठी',
    rtl: false,
  },
  mh: {
    iso: 'mh',
    english: 'Marshallese',
    local: 'Kajin M̧ajeļ',
    rtl: false,
  },
  mn: {
    iso: 'mn',
    english: 'Mongolian',
    local: 'Монгол хэл',
    rtl: false,
  },
  na: {
    iso: 'na',
    english: 'Nauru',
    local: 'Dorerin Naoero',
    rtl: false,
  },
  nv: {
    iso: 'nv',
    english: 'Navajo',
    local: 'Diné bizaad',
    rtl: false,
  },
  nd: {
    iso: 'nd',
    english: 'North Ndebele',
    local: 'isiNdebele',
    rtl: false,
  },
  ne: {
    iso: 'ne',
    english: 'Nepali',
    local: 'नेपाली',
    rtl: false,
  },
  ng: {
    iso: 'ng',
    english: 'Ndonga',
    local: 'Owambo',
    rtl: false,
  },
  nb: {
    iso: 'nb',
    english: 'Norwegian Bokmål',
    local: 'Norsk Bokmål',
    rtl: false,
  },
  nn: {
    iso: 'nn',
    english: 'Norwegian Nynorsk',
    local: 'Norsk Nynorsk',
    rtl: false,
  },
  no: {
    iso: 'no',
    english: 'Norwegian',
    local: 'Norsk',
    rtl: false,
  },
  ii: {
    iso: 'ii',
    english: 'Sichuan Yi',
    local: 'ꆈꌠ꒿ Nuosuhxop',
    rtl: false,
  },
  nr: {
    iso: 'nr',
    english: 'South Ndebele',
    local: 'isiNdebele',
    rtl: false,
  },
  oc: {
    iso: 'oc',
    english: 'Occitan',
    local: 'occitan',
    rtl: false,
  },
  oj: {
    iso: 'oj',
    english: 'Ojibwa',
    local: 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
    rtl: false,
  },
  cu: {
    iso: 'cu',
    english: 'Slavic',
    local: 'ѩзыкъ словѣньскъ',
    rtl: false,
  },
  om: {
    iso: 'om',
    english: 'Oromo',
    local: 'Afaan Oromoo',
    rtl: false,
  },
  or: {
    iso: 'or',
    english: 'Oriya',
    local: 'ଓଡ଼ିଆ',
    rtl: false,
  },
  os: {
    iso: 'os',
    english: 'Ossetian',
    local: 'ирон æвзаг',
    rtl: false,
  },
  pa: {
    iso: 'pa',
    english: 'Punjabi',
    local: 'ਪੰਜਾਬੀ, پنجابی‎',
    rtl: false,
  },
  pi: {
    iso: 'pi',
    english: 'Pali',
    local: 'पालि',
    rtl: false,
  },
  fa: {
    iso: 'fa',
    english: 'Persian',
    local: 'فارسی',
    rtl: true,
  },
  pl: {
    iso: 'pl',
    english: 'Polish',
    local: 'język polski',
    rtl: false,
  },
  ps: {
    iso: 'ps',
    english: 'Pashto',
    local: 'پښتو',
    rtl: false,
  },
  pt: {
    iso: 'pt',
    english: 'Portuguese',
    local: 'Português',
    rtl: false,
  },
  qu: {
    iso: 'qu',
    english: 'Quechua',
    local: 'Runa Simi',
    rtl: false,
  },
  rm: {
    iso: 'rm',
    english: 'Romansh',
    local: 'Rumantsch Grischun',
    rtl: false,
  },
  rn: {
    iso: 'rn',
    english: 'Rundi',
    local: 'Ikirundi',
    rtl: false,
  },
  ro: {
    iso: 'ro',
    english: 'Romanian',
    local: 'Română',
    rtl: false,
  },
  ru: {
    iso: 'ru',
    english: 'Russian',
    local: 'русский',
    rtl: false,
  },
  sa: {
    iso: 'sa',
    english: 'Sanskrit',
    local: 'संस्कृतम्',
    rtl: false,
  },
  sc: {
    iso: 'sc',
    english: 'Sardinian',
    local: 'sardu',
    rtl: false,
  },
  sd: {
    iso: 'sd',
    english: 'Sindhi',
    local: 'सिन्धी, سنڌي، سندھی‎',
    rtl: false,
  },
  se: {
    iso: 'se',
    english: 'Northern Sami',
    local: 'Davvisámegiella',
    rtl: false,
  },
  sm: {
    iso: 'sm',
    english: 'Samoan',
    local: "gagana fa'a Samoa",
    rtl: false,
  },
  sg: {
    iso: 'sg',
    english: 'Sango',
    local: 'yângâ tî sängö',
    rtl: false,
  },
  sr: {
    iso: 'sr',
    english: 'Serbian',
    local: 'српски језик',
    rtl: false,
  },
  gd: {
    iso: 'gd',
    english: 'Scottish Gaelic',
    local: 'Gàidhlig',
    rtl: false,
  },
  sn: {
    iso: 'sn',
    english: 'Shona',
    local: 'chiShona',
    rtl: false,
  },
  si: {
    iso: 'si',
    english: 'Sinhala',
    local: 'සිංහල',
    rtl: false,
  },
  sk: {
    iso: 'sk',
    english: 'Slovak',
    local: 'Slovenčina',
    rtl: false,
  },
  sl: {
    iso: 'sl',
    english: 'Slovenian',
    local: 'Slovenski Jezik',
    rtl: false,
  },
  so: {
    iso: 'so',
    english: 'Somali',
    local: 'Soomaaliga',
    rtl: false,
  },
  st: {
    iso: 'st',
    english: 'Southern Sotho',
    local: 'Sesotho',
    rtl: false,
  },
  es: {
    iso: 'es',
    english: 'Spanish',
    local: 'Español',
    rtl: false,
  },
  su: {
    iso: 'su',
    english: 'Sundanese',
    local: 'Basa Sunda',
    rtl: false,
  },
  sw: {
    iso: 'sw',
    english: 'Swahili',
    local: 'Kiswahili',
    rtl: false,
  },
  ss: {
    iso: 'ss',
    english: 'Swati',
    local: 'SiSwati',
    rtl: false,
  },
  sv: {
    iso: 'sv',
    english: 'Swedish',
    local: 'Svenska',
    rtl: false,
  },
  ta: {
    iso: 'ta',
    english: 'Tamil',
    local: 'தமிழ்',
    rtl: false,
  },
  te: {
    iso: 'te',
    english: 'Telugu',
    local: 'తెలుగు',
    rtl: false,
  },
  tg: {
    iso: 'tg',
    english: 'Tajik',
    local: 'тоҷикӣ',
    rtl: false,
  },
  th: {
    iso: 'th',
    english: 'Thai',
    local: 'ไทย',
    rtl: false,
  },
  ti: {
    iso: 'ti',
    english: 'Tigrinya',
    local: 'ትግርኛ',
    rtl: false,
  },
  bo: {
    iso: 'bo',
    english: 'Tibetan',
    local: 'བོད་ཡིག',
    rtl: false,
  },
  tk: {
    iso: 'tk',
    english: 'Turkmen',
    local: 'Türkmen',
    rtl: false,
  },
  tl: {
    iso: 'tl',
    english: 'Tagalog',
    local: 'Wikang Tagalog',
    rtl: false,
  },
  tn: {
    iso: 'tn',
    english: 'Tswana',
    local: 'Setswana',
    rtl: false,
  },
  to: {
    iso: 'to',
    english: 'Tonga (Tonga Islands)',
    local: 'Faka Tonga',
    rtl: false,
  },
  tr: {
    iso: 'tr',
    english: 'Turkish',
    local: 'Türkçe',
    rtl: false,
  },
  ts: {
    iso: 'ts',
    english: 'Tsonga',
    local: 'Xitsonga',
    rtl: false,
  },
  tt: {
    iso: 'tt',
    english: 'Tatar',
    local: 'татар теле, tatar tele',
    rtl: false,
  },
  tw: {
    iso: 'tw',
    english: 'Twi',
    local: 'Twi',
    rtl: false,
  },
  ty: {
    iso: 'ty',
    english: 'Tahitian',
    local: 'Reo Tahiti',
    rtl: false,
  },
  ug: {
    iso: 'ug',
    english: 'Uighur',
    local: 'ئۇيغۇرچە',
    rtl: false,
  },
  uk: {
    iso: 'uk',
    english: 'Ukrainian',
    local: 'Українська',
    rtl: false,
  },
  ur: {
    iso: 'ur',
    english: 'Urdu',
    local: 'اردو',
    rtl: true,
  },
  uz: {
    iso: 'uz',
    english: 'Uzbek',
    local: 'Oʻzbek',
    rtl: false,
  },
  ve: {
    iso: 've',
    english: 'Venda',
    local: 'Tshivenḓa',
    rtl: false,
  },
  vi: {
    iso: 'vi',
    english: 'Vietnamese',
    local: 'Tiếng Việt',
    rtl: false,
  },
  vo: {
    iso: 'vo',
    english: 'Volapük',
    local: 'Volapük',
    rtl: false,
  },
  wa: {
    iso: 'wa',
    english: 'Walloon',
    local: 'Walon',
    rtl: false,
  },
  cy: {
    iso: 'cy',
    english: 'Welsh',
    local: 'Cymraeg',
    rtl: false,
  },
  wo: {
    iso: 'wo',
    english: 'Wolof',
    local: 'Wollof',
    rtl: false,
  },
  fy: {
    iso: 'fy',
    english: 'Western Frisian',
    local: 'Frysk',
    rtl: false,
  },
  xh: {
    iso: 'xh',
    english: 'Xhosa',
    local: 'isiXhosa',
    rtl: false,
  },
  yi: {
    iso: 'yi',
    english: 'Yiddish',
    local: 'ייִדיש',
    rtl: false,
  },
  yo: {
    iso: 'yo',
    english: 'Yoruba',
    local: 'Yorùbá',
    rtl: false,
  },
  za: {
    iso: 'za',
    english: 'Zhuang',
    local: 'Saɯ cueŋƅ',
    rtl: false,
  },
  zu: {
    iso: 'zu',
    english: 'Zulu',
    local: 'isiZulu',
    rtl: false,
  },
} as Record<
  string,
  {
    iso: string
    english: string
    local: string
    rtl: boolean
  }
>
